### ISSUE TITLE
Running Under `NODE_ENV=test` Errors with "NextRouter was not mounted"

### ISSUE THREAD

**Issue by nbibler** [amannn/next-query-params#40]
**Describe the bug**

Standing up a new NextJS 13 application, using the Pages router, adding this library, and running under `NODE_ENV=test` errors immediately with:

```
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted

Object.useRouter         in /node_modules/next/dist/client/router.js  (146:15)
exports.NextAdapterPages in /node_modules/next-query-params/dist/NextAdapterPages-b4b86ccd.js (1:293)
```

This does not appear to be an issue when `NODE_ENV=development` nor `NODE_ENV=production` (via `npm run build && NODE_ENV=production npm run start`.

**To Reproduce**

1. `npx create-next-app@^13.0.0`, do not use the App Router and switch into the new directory,
2. `npm install --save next-query-params use-query-params`,
3. Modify the `_app.tsx` to:
```diff
 import '@/styles/globals.css'
 import type { AppProps } from 'next/app'
+import NextAdapterPages from "next-query-params/pages";
+import { QueryParamProvider } from "use-query-params";
 
 export default function App({ Component, pageProps }: AppProps) {
-  return <Component {...pageProps} />
+  return (
+    <QueryParamProvider adapter={NextAdapterPages}>
+      <Component {...pageProps} />
+    </QueryParamProvider>
+  );
 }
```
4. Run the app under `NODE_ENV=test npm run dev`

**Expected behavior**

There should not be a NextRouter error and the application should display the generic NextJS welcome page.

**Comment by nbibler** [comment]
This error also occurs in NextJS 14.0.1 using the same steps provided above, but with `npx create-next-app@latest`.

**Comment by n-d-r-d-g** [comment]
Hi @nbibler,

I was experiencing the same issue. I fixed it by upgrading the following packages:
```
"next-query-params": "^5.0.0",
"use-query-params": "^2.2.1"
```

Note: I'm using `"next": "14.0.4"`.

**Comment by mifrej** [comment]
I'm having this issue even with the above versions mentioned by @n-d-r-d-g

**Comment by klausbadelt** [comment]
This doesn't just happen with NODE_ENV=test.  @n-d-r-d-g 's suggestion doesn't fix. We're on next@14.1.0 and next-query-params@5.0.0

Seems `router.isReady` should checked before using the router here:
 https://github.com/amannn/next-query-params/blob/a0472ff80e5e71c42a2d8547bcc20ad7d7c2b814/packages/next-query-params/src/NextAdapterPages.tsx#L14

Our workaround is currently to use a custom wrapper around QueryParamProvider like this:
```js
export const NextQueryParamProvider = ({ children }) => {
  const router = useRouter()

  return router.isReady ? (
    <QueryParamProvider adapter={NextAdapterPages} options={{ removeDefaultsFromUrl: true }}>
      {children}
    </QueryParamProvider>
  ) : children
}
```

Hopefully we'll have time to submit a PR. Thanks for a very useful library @amannn !

**Comment by l0gicgate** [comment]
@klausbadelt I believe I found the root cause. Your workaround doesn't work in our app, only in `NODE_ENV=TEST` for some reason though.

After further investigation, it appears that there's an issue with the way this package is bundled.

The RequireJS version of this package fails in dev. If I simply replace the source from the `b4b86ccd` bundle with the `293777d9` bundle which is ES6, the error disappears.

The one bundle uses `require` while the other one uses `import`. It's the only visible difference.

**b4b86ccd bundle uses require (doesn't work):**
![CleanShot 2024-10-15 at 22 05 23@2x](https://github.com/user-attachments/assets/c8145cd7-78da-4187-8ee6-e4a317142397)

**293777d9 bundle uses import (works):**
![CleanShot 2024-10-15 at 22 06 12@2x](https://github.com/user-attachments/assets/4a1f1e3b-9189-437e-bbed-47882715b7e5)

![CleanShot 2024-10-15 at 21 55 00@2x](https://github.com/user-attachments/assets/9a37c240-baec-41f2-918a-d345238818fc)
